version: '3.5'
services:
  nginx:
    image: nginx:1.15.8
    container_name: doc_nginx
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
